In [18]:
import numpy as np
import time
#python list
size = 1_000_000
list1 = list(range(size))  # list1 = [0,1,2,3,4,.....999999]
list2 = list(range(size))   # list2 = [0,1,2,3,4,.....999999]
result = []  # we are creating a empty list where we will save the values
start = time.time()  
for x,y in  zip(list1,list2):  # zip(list1, list2) -=> [(0,0),(1,1)....]
    result.append(x+y)
    #print(value)
    #print(result)
end = time.time()
print("python list addition time : ", end - start)

#numpy array
arr1 = np.array(list1)
arr2 = np.array(list2)
start = time.time()
result = arr1 + arr2 
print(result)
end = time.time()
print("python numpy addition time : ", end - start)







python list addition time :  0.09072113037109375
[      0       2       4 ... 1999994 1999996 1999998]
python numpy addition time :  0.011578798294067383


In [28]:
# create numpy arrays
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])  #1D array
print(arr1)
print(type(arr1))

# creating 2D array
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

arr3 = np.array([["Akshat","M",50], ["raman","M",12], ["John","M",12]])
print(arr3)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[['Akshat' 'M' '50']
 ['raman' 'M' '12']
 ['John' 'M' '12']]


In [ ]:
# create a Numpy array with values 10 to 100 and print its shape 

In [31]:
import numpy as np
list1 = list(range(10,100))
print(list1)
numpy_array = np.array(list1)
print(numpy_array.shape)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
(90,)


In [32]:
#Create 3x3 array of zero
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])